// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvq9VQHLKYSx4nEjiyHsehasKpFZNGD6Y',
    appId: '1:389730931635:web:cde4f017b59e878f3531c6',
    messagingSenderId: '389730931635',
    projectId: 'volunteercoord-ebd2d',
    authDomain: 'volunteercoord-ebd2d.firebaseapp.com',
    storageBucket: 'volunteercoord-ebd2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6fqmgpvpotmJnIOVZsBFbVPrWy4qyx0',
    appId: '1:389730931635:android:c7b98614369f24923531c6',
    messagingSenderId: '389730931635',
    projectId: 'volunteercoord-ebd2d',
    storageBucket: 'volunteercoord-ebd2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4YS7klEGl9qpyQU9zC1wRohVOHizO8I',
    appId: '1:389730931635:ios:0880ebe4a918cc3d3531c6',
    messagingSenderId: '389730931635',
    projectId: 'volunteercoord-ebd2d',
    storageBucket: 'volunteercoord-ebd2d.firebasestorage.app',
    iosBundleId: 'com.example.volunteer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4YS7klEGl9qpyQU9zC1wRohVOHizO8I',
    appId: '1:389730931635:ios:0880ebe4a918cc3d3531c6',
    messagingSenderId: '389730931635',
    projectId: 'volunteercoord-ebd2d',
    storageBucket: 'volunteercoord-ebd2d.firebasestorage.app',
    iosBundleId: 'com.example.volunteer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvq9VQHLKYSx4nEjiyHsehasKpFZNGD6Y',
    appId: '1:389730931635:web:48350a5f542845be3531c6',
    messagingSenderId: '389730931635',
    projectId: 'volunteercoord-ebd2d',
    authDomain: 'volunteercoord-ebd2d.firebaseapp.com',
    storageBucket: 'volunteercoord-ebd2d.firebasestorage.app',
  );
}
